// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatchDownload() {
  return window['go']['main']['App']['CancelBatchDownload']();
}

export function CheckBinaries() {
  return window['go']['main']['App']['CheckBinaries']();
}

export function CheckPlaylist(arg1) {
  return window['go']['main']['App']['CheckPlaylist'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function GetVersionStatus() {
  return window['go']['main']['App']['GetVersionStatus']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function LaunchSetupTerminal() {
  return window['go']['main']['App']['LaunchSetupTerminal']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenSaveFolder(arg1) {
  return window['go']['main']['App']['OpenSaveFolder'](arg1);
}

export function PauseBatchDownload() {
  return window['go']['main']['App']['PauseBatchDownload']();
}

export function ResumeBatchDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResumeBatchDownload'](arg1, arg2, arg3, arg4);
}

export function RetryDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetryDownload'](arg1, arg2, arg3, arg4);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetTemporaryYouTubeCookie(arg1) {
  return window['go']['main']['App']['SetTemporaryYouTubeCookie'](arg1);
}

export function StartBatchDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBatchDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartCompression(arg1, arg2) {
  return window['go']['main']['App']['StartCompression'](arg1, arg2);
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function UpgradeBinary(arg1) {
  return window['go']['main']['App']['UpgradeBinary'](arg1);
}

export function ValidateURL(arg1) {
  return window['go']['main']['App']['ValidateURL'](arg1);
}
