// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatchDownload() {
  return window['go']['main']['App']['CancelBatchDownload']();
}

export function CancelGalleryDownload() {
  return window['go']['main']['App']['CancelGalleryDownload']();
}

export function CheckBinaries() {
  return window['go']['main']['App']['CheckBinaries']();
}

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function CheckPlaylist(arg1) {
  return window['go']['main']['App']['CheckPlaylist'](arg1);
}

export function ClearCookieConfig() {
  return window['go']['main']['App']['ClearCookieConfig']();
}

export function DismissRestrictedFailures() {
  return window['go']['main']['App']['DismissRestrictedFailures']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAppUpdateInfo() {
  return window['go']['main']['App']['GetAppUpdateInfo']();
}

export function GetAvailableBrowsers() {
  return window['go']['main']['App']['GetAvailableBrowsers']();
}

export function GetBrewInstallStatus() {
  return window['go']['main']['App']['GetBrewInstallStatus']();
}

export function GetCookieConfig() {
  return window['go']['main']['App']['GetCookieConfig']();
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function GetVersionStatus() {
  return window['go']['main']['App']['GetVersionStatus']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function InstallAppUpdate() {
  return window['go']['main']['App']['InstallAppUpdate']();
}

export function InstallDependencies(arg1) {
  return window['go']['main']['App']['InstallDependencies'](arg1);
}

export function LaunchSetupTerminal() {
  return window['go']['main']['App']['LaunchSetupTerminal']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenSaveFolder(arg1) {
  return window['go']['main']['App']['OpenSaveFolder'](arg1);
}

export function PauseBatchDownload() {
  return window['go']['main']['App']['PauseBatchDownload']();
}

export function PromptToInstallDependencies() {
  return window['go']['main']['App']['PromptToInstallDependencies']();
}

export function ResumeBatchDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResumeBatchDownload'](arg1, arg2, arg3, arg4);
}

export function RetryDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetryDownload'](arg1, arg2, arg3, arg4);
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetGalleryCookie(arg1) {
  return window['go']['main']['App']['SetGalleryCookie'](arg1);
}

export function SetManualCookie(arg1) {
  return window['go']['main']['App']['SetManualCookie'](arg1);
}

export function SetTemporaryYouTubeCookie(arg1) {
  return window['go']['main']['App']['SetTemporaryYouTubeCookie'](arg1);
}

export function StartBatchDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBatchDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function StartCompression(arg1, arg2) {
  return window['go']['main']['App']['StartCompression'](arg1, arg2);
}

export function StartDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4);
}

export function StartGalleryBatchDownload(arg1, arg2) {
  return window['go']['main']['App']['StartGalleryBatchDownload'](arg1, arg2);
}

export function StartGalleryDownload(arg1, arg2) {
  return window['go']['main']['App']['StartGalleryDownload'](arg1, arg2);
}

export function UpdateCookieConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateCookieConfig'](arg1, arg2);
}

export function UpgradeBinary(arg1) {
  return window['go']['main']['App']['UpgradeBinary'](arg1);
}

export function ValidateURL(arg1) {
  return window['go']['main']['App']['ValidateURL'](arg1);
}
