// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckBinaries():Promise<Record<string, any>>;

export function CheckPlaylist(arg1:string):Promise<Record<string, any>>;

export function GetDefaultSavePath():Promise<string>;

export function GetVersionStatus():Promise<Array<main.BinaryVersion>>;

export function GetVideoTitle(arg1:string):Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function RetryDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectFiles(arg1:string):Promise<Array<string>>;

export function SelectFolder(arg1:string):Promise<Array<string>>;

export function StartBatchDownload(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartCompression(arg1:Array<string>,arg2:main.CompressionOptions):Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function UpgradeBinary(arg1:string):Promise<void>;

export function ValidateURL(arg1:string):Promise<boolean>;
