// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelBatchDownload():Promise<void>;

export function CancelGalleryDownload():Promise<void>;

export function CheckBinaries():Promise<Record<string, any>>;

export function CheckDependencies():Promise<main.DependencyCheckResult>;

export function CheckPlaylist(arg1:string):Promise<Record<string, any>>;

export function ClearCookieConfig():Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAppUpdateInfo():Promise<main.AppUpdateInfo>;

export function GetAvailableBrowsers():Promise<Array<string>>;

export function GetBrewInstallStatus():Promise<Record<string, any>>;

export function GetCookieConfig():Promise<main.CookieConfig>;

export function GetDefaultSavePath():Promise<string>;

export function GetVersionStatus():Promise<Array<main.BinaryVersion>>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function InstallAppUpdate():Promise<void>;

export function InstallDependencies(arg1:Array<string>):Promise<boolean|string>;

export function LaunchSetupTerminal():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function OpenSaveFolder(arg1:string):Promise<void>;

export function PauseBatchDownload():Promise<void>;

export function PromptToInstallDependencies():Promise<boolean|string>;

export function ResumeBatchDownload(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function RetryDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectFiles(arg1:string):Promise<Array<string>>;

export function SelectFolder(arg1:string):Promise<Array<string>>;

export function SetGalleryCookie(arg1:string):Promise<void>;

export function SetManualCookie(arg1:string):Promise<void>;

export function SetTemporaryYouTubeCookie(arg1:string):Promise<void>;

export function StartBatchDownload(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function StartDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartGalleryBatchDownload(arg1:Array<string>,arg2:main.GalleryDownloadOptions):Promise<string>;

export function StartGalleryDownload(arg1:string,arg2:string):Promise<string>;

export function UpdateCookieConfig(arg1:string,arg2:string):Promise<void>;

export function UpgradeBinary(arg1:string):Promise<void>;

export function ValidateURL(arg1:string):Promise<boolean>;
